server:
  port: 7070
  context-path: /

spring:
  application:
    name: eWallet
  
  datasource:
    username: root
    password: 1qaz!QAZ
    url: jdbc:mysql://localhost:3306/ewallet
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    