server:
  port: 8080
  context-path: /

spring:
  application:
    name: eWallet
  
  datasource:
    username: root
    password: 1qaz!QAZ
    url: jdbc:mysql://localhost:3306/ewallet
    driver-class-name: com.mysql.jdbc.Driver  